# Generated by Django 4.2.1 on 2025-08-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_quote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
